#!/bin/bash
# Copyright (C) 2017 Luis R. Rodriguez <mcgrof@kernel.org>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of copyleft-next (version 0.3.1 or later) as published
# at http://copyleft-next.org/.

VDE_SOCKET="/var/run/qemu-vde.ctl"
ISO_PATH="/opt/isos"
ISO="$ISO_PATH/opensuse/openSUSE-Leap-42.2-DVD-x86_64-Build0215-Media.iso"
NEXT_TARGET="/opt/qemu/linux-next.qcow2"
USE_NEXT_TARGET="-hdb $NEXT_TARGET"
TARGET="/opt/qemu/opensuse-leap-42.2.img"
QEMU=$(which qemu-system-x86_64)

if [[ "$1" == "-i" ]]; then
	ISO="$2"
fi

function usage()
{
	echo -e "Usage $0 [ -i path-to-some-iso | -t path-to-some-img ]"
	echo -e ""
	echo -e "-i -- Use the specified file as the ISO we will boot from"
	echo -e "-t -- Use the specified file as the disk image target"
	echo -e "-n -- Use the specified file as the linux-next disk image target"
	echo -e "-l -- List available ISO files"
	echo -e "-d -- Use development version of qemu"
	echo -e ""
	echo -e "For example valid uses:"
	echo -e "\t$0 -i $ISO -t $TARGET"
	echo -e "\t$0 -l"
	echo -e ""
}

function parse_args()
{
	case $1 in
		"--help")
			usage
			exit 1
			;;
		"-h")
			usage
			exit 1
			;;
		"-d")
			QEMU="$HOME/devel/qemu/x86_64-softmmu/qemu-system-x86_64"
			parse_args $@
			;;
		"-i")
			shift
			ISO=$1
			parse_args $@
			;;
		"-t")
			shift
			TARGET=$1
			parse_args $@
			;;
		"-n")
			shift
			NEXT_TARGET=$1
			if [[ "$NEXT_TARGET" == "none" ]]; then
				USE_NEXT_TARGET=""
			else
				USE_NEXT_TARGET="-hdb $NEXT_TARGET"
			fi
			parse_args $@
			;;
		"-l")
			parse_args $@
			;;
		*)
			;;
	esac
}

parse_args $@

kvm=(
	$QEMU
	-cpu kvm64
	-enable-kvm
	#-kernel $kernel
	-m 1024
	-smp 1
	-netdev vde,sock=$VDE_SOCKET,group=kvm,mode=0660,id=vde0                
	-device e1000,netdev=vde0,mac=52:54:00:12:34:84 
	-no-reboot
	-cdrom $ISO
	-watchdog i6300esb
	-rtc base=localtime
	-hda $TARGET
	$USE_NEXT_TARGET
	-boot order=d
)

"${kvm[@]}"
